<?php
$headerHtml = "";
$this->display("section/header.phtml", array("headerHtml" => $headerHtml));
?>
<?php $this->display("section/left.phtml"); ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                IAD管理平台
                <small>文字、水印等</small>
            </h1>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row" style="min-height:400px;margin: 10px">
                <div>
                    <h3>
                        使用说明
                    </h3>
                    <p>
                        左侧为菜单栏，右侧为数据编辑区域，单击左侧的菜单栏开始你的探索
                    </p>
                </div>
                <div>
                    <h3>我的常用功能</h3>
                    <div class="col-md-3 col-sm-6 col-xs-12" onclick="window.location.href='/index';">
                        <div class="info-box bg-aqua">
                            <span class="info-box-icon"><i class="fa fa-bookmark-o"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text">图片管理</span>
                                <span class="info-box-number"></span>
                                <div class="progress">
                                    <div class="progress-bar" style="width: 100%"></div>
                                </div>
                            <span class="progress-description">
                                图片管理
                            </span>
                            </div><!-- /.info-box-content -->
                        </div><!-- /.info-box -->
                    </div>

                    <div class="col-md-3 col-sm-6 col-xs-12" onclick="window.location.href='/index';">
                        <div class="info-box bg-aqua">
                            <span class="info-box-icon"><i class="fa fa-bookmark-o"></i></span>
                            <div class="info-box-content">
                                <span class="info-box-text">文字管理</span>
                                <span class="info-box-number"></span>
                                <div class="progress">
                                    <div class="progress-bar" style="width: 100%"></div>
                                </div>
                            <span class="progress-description">
                                文字管理
                            </span>
                            </div><!-- /.info-box-content -->
                        </div><!-- /.info-box -->
                    </div>
                </div>
            </div>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
<?php $this->display("section/footer.phtml"); ?>
