<div id="div-cartype-select" class="modal fade" style="z-index:10000">
    <div class="modal-dialog" style="width:800px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="row">

                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/template" id="cartype_select_template">
    <% _.each(carTypeList, function(cartype) { %>
    <button type="button" data-id="<%=cartype.car_type_id%>" class="btn btn-default city-node"><%=cartype.name%></button>
    <% }); %>
</script>