<div id="div-city-select" class="modal fade" style="z-index:10000">
    <div class="modal-dialog" style="width:800px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <div class="row">

                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/template" id="city_select_template">
    <button type="button" data-id="" class="btn btn-default city-node">全部城市</button>
    <% _.each(cityList, function(city) { %>
    <button type="button" data-id="<%=city.short%>" class="btn btn-default city-node"><%=city.cn%></button>
    <% }); %>
</script>