<!-- system modal start -->
<div id="lm-alert" class="modal">
    <div class="modal-dialog modal-sm" style="top:100px">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h5 class="modal-title"><i class="fa fa-exclamation-circle"></i> [Title]</h5>
            </div>
            <div class="modal-body small">
                <p>[Message]</p>
            </div>
            <div class="modal-footer" >
                <button type="button" class="btn btn-primary ok" data-dismiss="modal">[BtnOk]</button>
                <button type="button" class="btn btn-default cancel" data-dismiss="modal">[BtnCancel]</button>
            </div>
        </div>
    </div>
</div>
<!-- system modal end -->

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 1.0.0
    </div>
    <strong>Copyright &copy; 2010-<?= date("Y", time())?> <a href="http://www.luomor.com">烙馍网</a>.</strong> All rights reserved.
</footer>
</div><!-- ./wrapper -->

<!-- jQuery 2.1.4 -->
<!--script src="/js/jQuery/jQuery-2.1.4.min.js"></script-->
<!-- jQuery UI 1.11.4 -->
<script src="/js/jQuery/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.5 -->
<script src="/js/bootstrap/bootstrap.min.js"></script>
<script src="/js/underscore.js"></script>
<script src="/js/admin.js"></script>
<script src="/js/index.js"></script>
<?php if(isset($this->footerHtml)):?>
    <?php echo $this->footerHtml;?>
<?php endif?>
</body>
</html>
