<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>IAD管理平台</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/css/bootstrap/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/font-awesome/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="/css/icons/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/css/adminLTE/AdminLTE.min.css">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="/css/adminLTE/skins/skin-purple-light.css">

    <link rel="stylesheet" href="/css/style.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="/js/app/html5shiv.min.js"></script>
    <script src="/js/app/respond.min.js"></script>
    <![endif]-->

    <!-- jQuery 2.1.4 -->
    <script src="/js/jQuery/jQuery-2.1.4.min.js"></script>
    <script src="/js/angular.min.js"></script>
    <script src="/js/app.js"></script>

    <?php if(isset($this->headerHtml)):?>
    <?php echo $this->headerHtml;?>
    <?php endif?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper" style="min-height: 600px">

    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini">IAD</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">IAD管理平台</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="<?=$ssoUrl?>" class="dropdown-toggle" target="_blank">
                            <span class="hidden-xs"><?=$operator?></span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
