<div class="fixed-table-pagination" style="display: block;">
    <div class="pull-left pagination-detail form-inline">
        <span class="pagination-info">共 <span class="total_count"></span> 条记录</span>
        <span class="pagination-info">第 <span class="current_page">1</span> 页</span>
        <span class="page-list">
            每页显示
            <select class="form-control number_per_page">
            </select>
            条记录
        </span>
        <span class="page-go-to">
            跳转到 <input type="text" id="page_number" name="page_number"/> 页
            <button type="button" class="btn btn-primary go-to-page">确定</button>
        </span>
    </div>
    <div class="pull-right pagination">
        <ul class="pagination">

        </ul>
    </div>
</div>